### ISSUE TITLE
Unexpected token U

### ISSUE THREAD

**Issue by AndrewRadayev** [andrewrynhard/atom-latex-plus#33] opened 2016-02-15 08:38 UTC
Hi, Andrew. I've got an issue and have no idea wht is problem. 
Configuration Error: Invalid parameter
Unexpected token U

So, my code:

`\documentclass[14pt,a4paper]{extarticle}
\usepackage[T2A]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage[russian]{babel}
\begin{document}
Hello\LaTeX{}!
\end{document}
`

I use win 10, actual ver of atom and your compiler.

**Comment by andrewrynhard** [comment] 2016-02-15 21:08
@AndrewRadayev this is a duplicate of #26. Unfortunately I have not had access to a development environment on Windows. The best I could do is push potential changes to another branch and have you pull changes until it is fixed. Or you can try to take a stab at the fix. Closing this since #26 is the same

**Closed as completed by andrewrynhard** 2016-02-15 21:08 UTC
Labels: duplicate
