### ISSUE TITLE
Symlinking Error when compiling

### ISSUE THREAD

**Issue by syed-islam** [andrewrynhard/atom-latex-plus#66] opened 2016-07-25 00:37 UTC
Error while symlinking /Volumes/Macintosh HD/Users/sislam/Publications/_4166655wjhdgh/it.synctex.gz to /Volumes/Macintosh HD/Users/sislam/Publications/_4166655wjhdgh/.latex/it.synctex.gz
Error: EINVAL: invalid argument, readlink '/Volumes/Macintosh HD/Users/sislam/Publications/_4166655wjhdgh/it.synctex.gz'
Error while symlinking /Volumes/Macintosh HD/Users/sislam/Publications/_4166655wjhdgh/it.pdf to /Volumes/Macintosh HD/Users/sislam/Publications/_4166655wjhdgh/.latex/it.pdf
Error: EINVAL: invalid argument, readlink '/Volumes/Macintosh HD/Users/sislam/Publications/_4166655wjhdgh/it.pdf'

**Comment by dpo** [comment] 2016-07-26 00:01
Duplicate of #58?

**Comment by andrewrynhard** [comment] 2016-10-15 12:56
Closed by #71

**Closed as completed by andrewrynhard** 2016-10-15 12:56 UTC
