### ISSUE TITLE
can not edit default setting

### ISSUE THREAD

**Issue by wxflogic** [andrewrynhard/atom-latex-plus#34] opened 2016-02-17 12:23 UTC
When I hit Cmd', it reports the following error:

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [latex-plus](https://github.com/andrewrynhard/atom-latex-plus) package, v0.8.3
### Stack Trace

Uncaught TypeError: Cannot read property 'edit' of undefined

```
At /Users/wxf/.atom/packages/latex-plus/lib/main.js:56

TypeError: Cannot read property 'edit' of undefined
    at atom-workspace.latexPlusEdit (/Users/wxf/.atom/packages/latex-plus/lib/main.js:56:21)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -8:22.1.0 core:save (atom-text-editor.editor.is-focused)
     -8:12.5.0 markdown-katex-preview:toggle (atom-text-editor.editor.is-focused)
  8x -8:03.4.0 core:undo (atom-text-editor.editor.is-focused)
  2x -7:58.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -7:54.3.0 core:save (atom-text-editor.editor.is-focused)
     -7:49 markdown-katex-preview:toggle (atom-text-editor.editor.is-focused)
  2x -7:39.8.0 core:undo (atom-text-editor.editor.is-focused)
     -2:11.1.0 tree-view:toggle (atom-text-editor.editor.is-focused)
  2x -1:50.4.0 latex-plus:edit (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:33 core:cancel (a.btn-issue.btn.btn-error)
  3x -0:30.1.0 markdown-writer:toggle-code-text (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -0:16.1.0 latex-plus:edit (atom-text-editor.editor.is-focused)
     -0:05.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:05.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:01.8.0 markdown-writer:toggle-code-text (atom-text-editor.editor.is-focused)
     -0:01.8.0 latex-plus:edit (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "markdown-preview",
      "ever-notedown",
      "markdown-preview-plus",
      "my-package",
      "latex-completions"
    ],
    "projectHome": "/Users/wxf/Documents/github"
  },
  "latex-plus": {
    "advancedEnabled": true,
    "bibtexEnabled": true,
    "shellEscapeEnabled": true,
    "synctexVertAlign": 0.5,
    "texBin": "/Library/TeX/texbin/"
  }
}
```
### Installed Packages

``` coffee
# User
atom-markdown-katex, v0.4.0
autocomplete-bibtex, v0.6.2
language-latex, v0.6.1
language-pfm, v0.82.0
latex, v0.29.0
latex-plus, v0.8.3
latexer, v0.2.7
linter, v1.11.3
markdown-folder, v0.5.0
markdown-table-formatter, v2.7.2
markdown-writer, v2.3.1
mathjax-wrapper, v0.1.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by andrewrynhard** [comment] 2016-02-17 18:15
@wxflogic duplicate of #28. I have a fix that I will push soon. Working on a few other things. The workaround for now is to first compile the project, then edit.

**Closed as completed by andrewrynhard** 2016-02-17 18:15 UTC
Labels: duplicate

**Comment by wxflogic** [comment] 2016-02-18 00:42
I managed to edit the setting as you suggested. Thanks for your great work.

Andrew Rynhard notifications@github.com于2016年2月18日周四 上午2:15写道：
